### ISSUE TITLE
error and update

### ISSUE THREAD

**Issue by Andyauk** [Marttins011/mt-fishing#1]
`        QBCore.Functions.Notify('You dont hit any fish', 'error', 7500)`
should that be!
`        QBCore.Functions.Notify('You dont have any fish', 'error', 7500)`
 also it don't post the message if you don't have any, 
and the rod get stuck in hands if you fail to catch.

maybe add this for the fish buyer blip.

```
Citizen.CreateThread(function()
    local blip = AddBlipForCoord(-1038.57, -1397.1, 4.55)
	SetBlipSprite(blip, 88)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 0.7)
	SetBlipAsShortRange(blip, true)
	SetBlipColour(blip, 37) -- Mudar cor aqui!
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentSubstringPlayerName("Fishing Buyer")
    EndTextCommandSetBlipName(blip)
end)
```

**Comment by Marttins011** [comment]
Thanks bro! <3
